/**
 * App Server
 * RADAR App Server Api Documentation
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {
  HttpClient,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse
} from '@angular/common/http'
import { Inject, Injectable, Optional } from '@angular/core'
import { Observable } from 'rxjs/Observable'

import {
  FcmUserDto,
  FcmUsers,
  ResponseEntity
} from '../../../shared/models/models'
import { Configuration } from './configuration'
import { CustomHttpUrlEncodingCodec } from './encoder'
import { BASE_PATH, COLLECTION_FORMATS } from './variables'

@Injectable()
export class RadarUserControllerService {
  protected basePath = 'http://localhost:8080'
  public defaultHeaders = new HttpHeaders()
  public configuration = new Configuration()

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath
    }
    if (configuration) {
      this.configuration = configuration
      this.basePath = basePath || configuration.basePath || this.basePath
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data'
    for (const consume of consumes) {
      if (form === consume) {
        return true
      }
    }
    return false
  }

  /**
   * addUserToProject
   *
   * @param projectId projectId
   * @param userDto userDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public addUserToProjectUsingPOST(
    projectId: string,
    userDto: FcmUserDto,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ResponseEntity>
  public addUserToProjectUsingPOST(
    projectId: string,
    userDto: FcmUserDto,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ResponseEntity>>
  public addUserToProjectUsingPOST(
    projectId: string,
    userDto: FcmUserDto,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ResponseEntity>>
  public addUserToProjectUsingPOST(
    projectId: string,
    userDto: FcmUserDto,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (projectId === null || projectId === undefined) {
      throw new Error(
        'Required parameter projectId was null or undefined when calling addUserToProjectUsingPOST.'
      )
    }

    if (userDto === null || userDto === undefined) {
      throw new Error(
        'Required parameter userDto was null or undefined when calling addUserToProjectUsingPOST.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json']
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.post<ResponseEntity>(
      `${this.basePath}/projects/${encodeURIComponent(
        String(projectId)
      )}/users`,
      userDto,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * addUser
   *
   * @param userDto userDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public addUserUsingPOST(
    userDto: FcmUserDto,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ResponseEntity>
  public addUserUsingPOST(
    userDto: FcmUserDto,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ResponseEntity>>
  public addUserUsingPOST(
    userDto: FcmUserDto,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ResponseEntity>>
  public addUserUsingPOST(
    userDto: FcmUserDto,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (userDto === null || userDto === undefined) {
      throw new Error(
        'Required parameter userDto was null or undefined when calling addUserUsingPOST.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json']
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.post<ResponseEntity>(
      `${this.basePath}/users`,
      userDto,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * getAllRadarUsers
   *
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAllRadarUsersUsingGET(
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<FcmUsers>
  public getAllRadarUsersUsingGET(
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<FcmUsers>>
  public getAllRadarUsersUsingGET(
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<FcmUsers>>
  public getAllRadarUsersUsingGET(
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []

    return this.httpClient.get<FcmUsers>(`${this.basePath}/users`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    })
  }

  /**
   * getRadarUserUsingId
   *
   * @param id id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getRadarUserUsingIdUsingGET(
    id?: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<FcmUserDto>
  public getRadarUserUsingIdUsingGET(
    id?: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<FcmUserDto>>
  public getRadarUserUsingIdUsingGET(
    id?: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<FcmUserDto>>
  public getRadarUserUsingIdUsingGET(
    id?: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.get<FcmUserDto>(`${this.basePath}/users/user`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress
    })
  }

  /**
   * getRadarUserUsingSubjectId
   *
   * @param subjectId subjectId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getRadarUserUsingSubjectIdUsingGET(
    subjectId: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<FcmUserDto>
  public getRadarUserUsingSubjectIdUsingGET(
    subjectId: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<FcmUserDto>>
  public getRadarUserUsingSubjectIdUsingGET(
    subjectId: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<FcmUserDto>>
  public getRadarUserUsingSubjectIdUsingGET(
    subjectId: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (subjectId === null || subjectId === undefined) {
      throw new Error(
        'Required parameter subjectId was null or undefined when calling getRadarUserUsingSubjectIdUsingGET.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []

    return this.httpClient.get<FcmUserDto>(
      `${this.basePath}/users/${encodeURIComponent(String(subjectId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * getUsersUsingProjectId
   *
   * @param projectId projectId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getUsersUsingProjectIdUsingGET(
    projectId: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<FcmUsers>
  public getUsersUsingProjectIdUsingGET(
    projectId: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<FcmUsers>>
  public getUsersUsingProjectIdUsingGET(
    projectId: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<FcmUsers>>
  public getUsersUsingProjectIdUsingGET(
    projectId: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (projectId === null || projectId === undefined) {
      throw new Error(
        'Required parameter projectId was null or undefined when calling getUsersUsingProjectIdUsingGET.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []

    return this.httpClient.get<FcmUsers>(
      `${this.basePath}/projects/${encodeURIComponent(
        String(projectId)
      )}/users`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * updateUserInProject
   *
   * @param projectId projectId
   * @param userDto userDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateUserInProjectUsingPUT(
    projectId: string,
    userDto: FcmUserDto,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ResponseEntity>
  public updateUserInProjectUsingPUT(
    projectId: string,
    userDto: FcmUserDto,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ResponseEntity>>
  public updateUserInProjectUsingPUT(
    projectId: string,
    userDto: FcmUserDto,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ResponseEntity>>
  public updateUserInProjectUsingPUT(
    projectId: string,
    userDto: FcmUserDto,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (projectId === null || projectId === undefined) {
      throw new Error(
        'Required parameter projectId was null or undefined when calling updateUserInProjectUsingPUT.'
      )
    }

    if (userDto === null || userDto === undefined) {
      throw new Error(
        'Required parameter userDto was null or undefined when calling updateUserInProjectUsingPUT.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json']
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.put<ResponseEntity>(
      `${this.basePath}/projects/${encodeURIComponent(
        String(projectId)
      )}/users`,
      userDto,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * updateUser
   *
   * @param userDto userDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateUserUsingPUT(
    userDto: FcmUserDto,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ResponseEntity>
  public updateUserUsingPUT(
    userDto: FcmUserDto,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ResponseEntity>>
  public updateUserUsingPUT(
    userDto: FcmUserDto,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ResponseEntity>>
  public updateUserUsingPUT(
    userDto: FcmUserDto,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (userDto === null || userDto === undefined) {
      throw new Error(
        'Required parameter userDto was null or undefined when calling updateUserUsingPUT.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['*/*']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json']
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.put<ResponseEntity>(
      `${this.basePath}/users`,
      userDto,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }
}
