export class LocKeys {
  static DEFAULT_NONE = new LocKeys('DEFAULT_NONE')
  static ENROL_WELCOME_1 = new LocKeys('ENROL_WELCOME_1')
  static ENROL_WELCOME_2 = new LocKeys('ENROL_WELCOME_2')
  static ENROL_WELCOME_DESC = new LocKeys('ENROL_WELCOME_DESC')
  static ENROL_REGISTRATION = new LocKeys('ENROL_REGISTRATION')
  static ENROL_REGISTRATION_DESC = new LocKeys('ENROL_REGISTRATION_DESC')
  static ENROL_PREFERENCES = new LocKeys('ENROL_PREFERENCES')
  static ENROL_PREFERENCES_DESC = new LocKeys('ENROL_PREFERENCES_DESC')
  static ENROL_REGISTRATION_COMPLETE = new LocKeys(
    'ENROL_REGISTRATION_COMPLETE'
  )
  static ENROL_REGISTRATION_COMPLETE_DESC = new LocKeys(
    'ENROL_REGISTRATION_COMPLETE_DESC'
  )
  static CALENDAR_TASK_MISSED_TITLE = new LocKeys('CALENDAR_TASK_MISSED_TITLE')
  static CALENDAR_TASK_MISSED_DESC = new LocKeys('CALENDAR_TASK_MISSED_DESC')
  static FINISH_THANKS = new LocKeys('FINISH_THANKS')
  static FINISH_NEXT_TASK_REMINDER = new LocKeys('FINISH_NEXT_TASK_REMINDER')
  static FINISH_COMPLETED_IN_CLINIC = new LocKeys('FINISH_COMPLETED_IN_CLINIC')
  static SETTINGS_SETTINGS = new LocKeys('SETTINGS_SETTINGS')
  static SETTINGS_PARTICIPANTID = new LocKeys('SETTINGS_PARTICIPANTID')
  static SETTINGS_PROJECTNAME = new LocKeys('SETTINGS_PROJECTNAME')
  static SETTINGS_USER_INFO = new LocKeys('SETTINGS_USER_INFO')
  static SETTINGS_ENROL_DATE = new LocKeys('SETTINGS_ENROL_DATE')
  static SETTINGS_LANGUAGE = new LocKeys('SETTINGS_LANGUAGE')
  static SETTINGS_LANGUAGE_ALERT = new LocKeys('SETTINGS_LANGUAGE_ALERT')
  static SETTINGS_NOTIFICATIONS = new LocKeys('SETTINGS_NOTIFICATIONS')
  static SETTINGS_NOTIFICATIONS_SOUND = new LocKeys(
    'SETTINGS_NOTIFICATIONS_SOUND'
  )
  static SETTINGS_NOTIFICATIONS_VIBRATION = new LocKeys(
    'SETTINGS_NOTIFICATIONS_VIBRATION'
  )
  static SETTINGS_NOTIFICATIONS_NIGHTMOD = new LocKeys(
    'SETTINGS_NOTIFICATIONS_NIGHTMOD'
  )
  static SETTINGS_NOTIFICATIONS_NIGHTMOD_DESC = new LocKeys(
    'SETTINGS_NOTIFICATIONS_NIGHTMOD_DESC'
  )
  static SETTINGS_REPORT = new LocKeys('SETTINGS_REPORT')
  static SETTINGS_VERSION = new LocKeys('SETTINGS_VERSION')
  static SETTINGS_CONFIGURATION = new LocKeys('SETTINGS_CONFIGURATION')
  static SETTINGS_SCHEDULE = new LocKeys('SETTINGS_SCHEDULE')
  static SETTINGS_RESET_ALERT = new LocKeys('SETTINGS_RESET_ALERT')
  static SETTINGS_RESET_ALERT_DESC = new LocKeys('SETTINGS_RESET_ALERT_DESC')
  static SETTINGS_RESET_ALERT_OPTION_DESC = new LocKeys(
    'SETTINGS_RESET_ALERT_OPTION_DESC'
  )
  static SETTINGS_RESET_ALERT_CONFIG_DESC = new LocKeys(
    'SETTINGS_RESET_ALERT_CONFIG_DESC'
  )
  static SETTINGS_RESET_ALERT_CACHE_DESC = new LocKeys(
    'SETTINGS_RESET_ALERT_CACHE_DESC'
  )
  static SETTINGS_RESET_ALERT_ENROLMENT_DESC = new LocKeys(
    'SETTINGS_RESET_ALERT_ENROLMENT_DESC'
  )
  static SETTINGS_ENROLMENT = new LocKeys('SETTINGS_ENROLMENT')
  static SETTINGS_CACHE = new LocKeys('SETTINGS_CACHE')
  static SETTINGS_CACHE_SIZE = new LocKeys('SETTINGS_CACHE_SIZE')
  static SETTINGS_LAST_UPLOAD_TO_SERVER = new LocKeys(
    'SETTINGS_LAST_UPLOAD_TO_SERVER'
  )
  static SETTINGS_SEND_CACHED_DATA = new LocKeys('SETTINGS_SEND_CACHED_DATA')
  static SETTINGS_WAIT_ALERT = new LocKeys('SETTINGS_WAIT_ALERT')
  static LANGUAGE_ENGLISH = new LocKeys('LANGUAGE_ENGLISH')
  static LANGUAGE_SPANISH = new LocKeys('LANGUAGE_SPANISH')
  static LANGUAGE_ITALIAN = new LocKeys('LANGUAGE_ITALIAN')
  static LANGUAGE_GERMAN = new LocKeys('LANGUAGE_GERMAN')
  static LANGUAGE_DANISH = new LocKeys('LANGUAGE_DANISH')
  static LANGUAGE_DUTCH = new LocKeys('LANGUAGE_DUTCH')
  static LANGUAGE_POLISH = new LocKeys('LANGUAGE_POLISH')
  static LANGUAGE_HEBREW = new LocKeys('LANGUAGE_HEBREW')
  static BTN_ENROL_ENROL = new LocKeys('BTN_ENROL_ENROL')
  static BTN_ENROL_SCAN = new LocKeys('BTN_ENROL_SCAN')
  static BTN_FINISH = new LocKeys('BTN_FINISH')
  static BTN_DONE = new LocKeys('BTN_DONE')
  static BTN_DISMISS = new LocKeys('BTN_DISMISS')
  static BTN_START = new LocKeys('BTN_START')
  static BTN_STOP = new LocKeys('BTN_STOP')
  static BTN_RESET = new LocKeys('BTN_RESET')
  static BTN_RETRY = new LocKeys('BTN_RETRY')
  static BTN_AGREE = new LocKeys('BTN_AGREE')
  static BTN_DISAGREE = new LocKeys('BTN_DISAGREE')
  static BTN_OKAY = new LocKeys('BTN_OKAY')
  static BTN_SET = new LocKeys('BTN_SET')
  static BTN_CANCEL = new LocKeys('BTN_CANCEL')
  static BTN_BEGIN = new LocKeys('BTN_BEGIN')
  static BTN_NEXT = new LocKeys('BTN_NEXT')
  static BTN_PREVIOUS = new LocKeys('BTN_PREVIOUS')
  static BTN_CLOSE = new LocKeys('BTN_CLOSE')
  static BTN_SELECT = new LocKeys('BTN_SELECT')
  static BTN_YES = new LocKeys('BTN_YES')
  static BTN_NO = new LocKeys('BTN_NO')
  static BTN_TRY_AGAIN = new LocKeys('BTN_TRY_AGAIN')
  static BTN_UPDATE = new LocKeys('BTN_UPDATE')
  static STATUS_LOADING = new LocKeys('STATUS_LOADING')
  static STATUS_SUCCESS = new LocKeys('STATUS_SUCCESS')
  static STATUS_FAILURE = new LocKeys('STATUS_FAILURE')
  static STATUS_NOW = new LocKeys('STATUS_NOW')
  static STATUS_UPDATE_AVAILABLE = new LocKeys('STATUS_UPDATE_AVAILABLE')
  static STATUS_UPDATE_AVAILABLE_DESC = new LocKeys(
    'STATUS_UPDATE_AVAILABLE_DESC'
  )
  static NOTIFICATION_TEST_REMINDER_NOW = new LocKeys(
    'NOTIFICATION_TEST_REMINDER_NOW'
  )
  static NOTIFICATION_TEST_REMINDER_NOW_DESC = new LocKeys(
    'NOTIFICATION_TEST_REMINDER_NOW_DESC'
  )
  static NOTIFICATION_REMINDER_SOON = new LocKeys('NOTIFICATION_REMINDER_SOON')
  static NOTIFICATION_REMINDER_SOON_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_SOON_DESC'
  )
  static NOTIFICATION_REMINDER_NOW = new LocKeys('NOTIFICATION_REMINDER_NOW')
  static NOTIFICATION_REMINDER_NOW_DESC_1 = new LocKeys(
    'NOTIFICATION_REMINDER_NOW_DESC_1'
  )
  static NOTIFICATION_REMINDER_NOW_DESC_2 = new LocKeys(
    'NOTIFICATION_REMINDER_NOW_DESC_2'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN_DESC'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN_ALERT_DEFAULT_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN_ALERT_DEFAULT_DESC'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN_ALERT_LASTOFNIGHT_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN_ALERT_LASTOFNIGHT_DESC'
  )
  static MEASURE_PROGRESS = new LocKeys('MEASURE_PROGRESS')
  static MEASURE_STEPS = new LocKeys('MEASURE_STEPS')
  static MEASURE_HEART_RATE = new LocKeys('MEASURE_HEART_RATE')
  static CREDITS_TITLE = new LocKeys('CREDITS_TITLE')
  static CREDITS_BODY = new LocKeys('CREDITS_BODY')
  static TASK_CALENDAR_TITLE = new LocKeys('TASK_CALENDAR_TITLE')
  static TASK_INFO_WARN = new LocKeys('TASK_INFO_WARN')
  static TASK_PROGRESS_COMPLETED = new LocKeys('TASK_PROGRESS_COMPLETED')
  static TASK_PROGRESS_TITLE = new LocKeys('TASK_PROGRESS_TITLE')
  static TASK_BAR_NEXT_TASK = new LocKeys('TASK_BAR_NEXT_TASK')
  static TASK_BAR_NOW_TASK = new LocKeys('TASK_BAR_NOW_TASK')
  static TASK_BAR_NEXT_TASK_SOON = new LocKeys('TASK_BAR_NEXT_TASK_SOON')
  static TASK_BAR_AFFIRMATION_1 = new LocKeys('TASK_BAR_AFFIRMATION_1')
  static TASK_BAR_AFFIRMATION_2 = new LocKeys('TASK_BAR_AFFIRMATION_2')
  static TASK_BAR_TASK_LEFT_1 = new LocKeys('TASK_BAR_TASK_LEFT_1')
  static TASK_BAR_TASK_LEFT_2 = new LocKeys('TASK_BAR_TASK_LEFT_2')
  static TASK_BAR_NO_TASK_1 = new LocKeys('TASK_BAR_NO_TASK_1')
  static TASK_BAR_NO_TASK_2 = new LocKeys('TASK_BAR_NO_TASK_2')
  static TASK_TIME_HOUR_SINGLE = new LocKeys('TASK_TIME_HOUR_SINGLE')
  static TASK_TIME_HOUR_MULTIPLE = new LocKeys('TASK_TIME_HOUR_MULTIPLE')
  static TASK_TIME_MINUTE_SINGLE = new LocKeys('TASK_TIME_MINUTE_SINGLE')
  static TASK_TIME_MINUTE_MULTIPLE = new LocKeys('TASK_TIME_MINUTE_MULTIPLE')
  static TESTING_NOTIFICATIONS = new LocKeys('TESTING_NOTIFICATIONS')
  static TESTING_NOTIFICATIONS_MESSAGE = new LocKeys(
    'TESTING_NOTIFICATIONS_MESSAGE'
  )
  static CLOSE_APP = new LocKeys('CLOSE_APP')
  static WARNING_DO_NOT_CLOSE_APP = new LocKeys('WARNING_DO_NOT_CLOSE_APP')
  static CONFIG_ERROR_DESC = new LocKeys('CONFIG_ERROR_DESC')
  static AUDIO_TASK_ALERT = new LocKeys('AUDIO_TASK_ALERT')
  static AUDIO_TASK_ALERT_DESC = new LocKeys('AUDIO_TASK_ALERT_DESC')
  static AUDIO_TASK_ATTEMPT_ALERT = new LocKeys('AUDIO_TASK_ATTEMPT_ALERT')
  static AUDIO_TASK_HAPPY_ALERT = new LocKeys('AUDIO_TASK_HAPPY_ALERT')
  static SPLASH_STATUS_UPDATING_CONFIG = new LocKeys(
    'SPLASH_STATUS_UPDATING_CONFIG'
  )
  static SPLASH_STATUS_SENDING_LOGS = new LocKeys('SPLASH_STATUS_SENDING_LOGS')
  
  static TXTIN_LABEL_DAY = new LocKeys('TXTIN_LABEL_DAY')
  static TXTIN_LABEL_MONTH = new LocKeys('TXTIN_LABEL_MONTH')
  static TXTIN_LABEL_YEAR = new LocKeys('TXTIN_LABEL_YEAR')
  static TXTIN_LABEL_HOUR = new LocKeys('TXTIN_LABEL_HOUR')
  static TXTIN_LABEL_MINUTE = new LocKeys('TXTIN_LABEL_MINUTE')
  static TXTIN_LABEL_SECOND = new LocKeys('TXTIN_LABEL_SECOND')
  static TXTIN_LABEL_AMPM = new LocKeys('TXTIN_LABEL_AMPM')

  static SD_TITLE_DIARY = new LocKeys('SD_TITLE_DIARY')
  static SD_INFO_BODY = new LocKeys('SD_INFO_BODY')
  static SD_TITLE_RECENT = new LocKeys('SD_TITLE_RECENT')
  static SD_TITLE_OLDER = new LocKeys('SD_TITLE_OLDER')
  static SD_DURATION = new LocKeys('SD_DURATION')
  static SD_CLEAR_TITLE = new LocKeys('SD_CLEAR_TITLE')
  static SD_CLEAR_MESSAGE = new LocKeys('SD_CLEAR_MESSAGE')
  static SD_LOADING_MESSAGE = new LocKeys('SD_LOADING_MESSAGE')
  static SD_LOADING_SUCCESS = new LocKeys('SD_LOADING_SUCCESS')
  static SD_ERROR_NETWORK = new LocKeys('SD_ERROR_NETWORK')
  static SD_ERROR_LOADING = new LocKeys('SD_ERROR_LOADING')
  static SD_ERROR_NEW = new LocKeys('SD_ERROR_NEW')
  static SD_NEW_TITLE = new LocKeys('SD_NEW_TITLE')
  static SD_NEW_MESSAGE = new LocKeys('SD_NEW_MESSAGE')
  static SD_DETAIL_TITLE = new LocKeys('SD_DETAIL_TITLE')
  static SD_DETAIL_1 = new LocKeys('SD_DETAIL_1')
  static SD_DETAIL_2 = new LocKeys('SD_DETAIL_2')
  static SD_DETAIL_3 = new LocKeys('SD_DETAIL_3')
  static SD_DETAIL_4 = new LocKeys('SD_DETAIL_4')
  static SD_DETAIL_5 = new LocKeys('SD_DETAIL_5')
  static SD_DETAIL_6 = new LocKeys('SD_DETAIL_6')
  static SD_DETAIL_7 = new LocKeys('SD_DETAIL_7')
  static SD_DETAIL_8 = new LocKeys('SD_DETAIL_8')
  static SD_DETAIL_9 = new LocKeys('SD_DETAIL_9')
  static SD_DETAIL_10 = new LocKeys('SD_DETAIL_10')
  static SD_DETAIL_11 = new LocKeys('SD_DETAIL_11')
  static SD_DETAIL_12 = new LocKeys('SD_DETAIL_12')
  static SD_RADIO_YES = new LocKeys('SD_RADIO_YES')
  static SD_RADIO_NO = new LocKeys('SD_RADIO_NO')
  static SD_RADIO_DONT_KNOW = new LocKeys('SD_RADIO_DONT_KNOW')
  static SD_RADIO_DETAIL_1 = new LocKeys('SD_RADIO_DETAIL_1')
  static SD_RADIO_DETAIL_2 = new LocKeys('SD_RADIO_DETAIL_2')
  static SD_RADIO_DETAIL_3 = new LocKeys('SD_RADIO_DETAIL_3')
  static SD_RADIO_DETAIL_4 = new LocKeys('SD_RADIO_DETAIL_4')
  static SD_RADIO_DETAIL_5 = new LocKeys('SD_RADIO_DETAIL_5')
  static SD_RADIO_DETAIL_6 = new LocKeys('SD_RADIO_DETAIL_6')
  static SD_RADIO_DETAIL_7 = new LocKeys('SD_RADIO_DETAIL_7')
  static SD_RADIO_DETAIL_DEFAULT = new LocKeys('SD_RADIO_DETAIL_DEFAULT')
  static SD_DURATION_MIN = new LocKeys('SD_DURATION_MIN')
  static SD_DURATION_MINS = new LocKeys('SD_DURATION_MINS')

  static DEQ_REDIRECT_MSG = new LocKeys('DEQ_REDIRECT_MSG')


  static CLINICAL_TASKS = new LocKeys('CLINICAL_TASKS')
  static ON_DEMAND_TASKS = new LocKeys('ON_DEMAND_TASKS')

  constructor(public value: string) {}

  toString() {
    return this.value
  }
}
