export class LocKeys {
  static DEFAULT_NONE = new LocKeys('DEFAULT_NONE')
  static ENROL_WELCOME_1 = new LocKeys('ENROL_WELCOME_1')
  static ENROL_WELCOME_2 = new LocKeys('ENROL_WELCOME_2')
  static ENROL_WELCOME_DESC = new LocKeys('ENROL_WELCOME_DESC')
  static ENROLE_STUDY_DESCRIPTION = new LocKeys('ENROLE_STUDY_DESCRIPTION')
  static ABOUT_STUDY_1 = new LocKeys('ABOUT_STUDY_1')
  static ABOUT_STUDY_2 = new LocKeys('ABOUT_STUDY_2')
  static ABOUT_HOW_THIS_STUDY_WORKS_Q = new LocKeys('ABOUT_HOW_THIS_STUDY_WORKS_Q')
  static ABOUT_HOW_THIS_STUDY_WORKS_ANS = new LocKeys('ABOUT_HOW_THIS_STUDY_WORKS_ANS')
  static ABOUT_WHO_IS_RUNNING_THIS_STUDY_Q = new LocKeys('ABOUT_WHO_IS_RUNNING_THIS_STUDY_Q')
  static ABOUT_WHO_IS_RUNNING_THIS_STUDY_ANS = new LocKeys('ABOUT_WHO_IS_RUNNING_THIS_STUDY_ANS')
  static ENROL_ABORT_THANKYOU_1 = new LocKeys('ENROL_ABORT_THANKYOU_1')
  static ENROL_ABORT_MESSAGE = new LocKeys('ENROL_ABORT_MESSAGE')
  static ENROL_ABOUT_HEADING = new LocKeys('ENROL_ABOUT_HEADING')
  static ENROL_HOW_STUDY_WORKS_HEADING = new LocKeys('ENROL_HOW_STUDY_WORKS_HEADING')
  static ENROL_ELIGIBILITY_HEADING = new LocKeys('ENROL_ELIGIBILITY_HEADING')
  static ENROL_REGISTRATION = new LocKeys('ENROL_REGISTRATION')
  static ENROL_REGISTRATION_DESC = new LocKeys('ENROL_REGISTRATION_DESC')
  static ENROL_PREFERENCES = new LocKeys('ENROL_PREFERENCES')
  static ENROL_PREFERENCES_DESC = new LocKeys('ENROL_PREFERENCES_DESC')
  static ENROL_REGISTRATION_COMPLETE = new LocKeys(
    'ENROL_REGISTRATION_COMPLETE'
  )
  static ENROL_REGISTRATION_COMPLETE_DESC = new LocKeys(
    'ENROL_REGISTRATION_COMPLETE_DESC'
  )
  static SURVEYS_HEADING = new LocKeys('SURVEYS_HEADING')
  static LEARN_HEADING = new LocKeys('LEARN_HEADING')
  static TODO_LIST_TITLE = new LocKeys('TODO_LIST_TITLE')
  static TODO_SELECT_INFO = new LocKeys('TODO_SELECT_INFO')
  static TODO_TIME_ESTIMATE_NOTICE = new LocKeys('TODO_TIME_ESTIMATE_NOTICE')
  static NO_SURVEYS_AVAILABLE = new LocKeys('NO_SURVEYS_AVAILABLE')
  static CALENDAR_ESM_MISSED_TITLE = new LocKeys('CALENDAR_ESM_MISSED_TITLE')
  static CALENDAR_ESM_MISSED_DESC = new LocKeys('CALENDAR_ESM_MISSED_DESC')
  static FINISH_THANKS = new LocKeys('FINISH_THANKS')
  static FINISH_NEXT_TASK_REMINDER = new LocKeys('FINISH_NEXT_TASK_REMINDER')
  static FINISH_COMPLETED_IN_CLINIC = new LocKeys('FINISH_COMPLETED_IN_CLINIC')
  static SETTINGS_SETTINGS = new LocKeys('SETTINGS_SETTINGS')
  static SETTINGS_PARTICIPANTID = new LocKeys('SETTINGS_PARTICIPANTID')
  static SETTINGS_PROJECTNAME = new LocKeys('SETTINGS_PROJECTNAME')
  static SETTINGS_USER_INFO = new LocKeys('SETTINGS_USER_INFO')
  static SETTINGS_ENROL_DATE = new LocKeys('SETTINGS_ENROL_DATE')
  static SETTINGS_LANGUAGE = new LocKeys('SETTINGS_LANGUAGE')
  static SETTINGS_LANGUAGE_ALERT = new LocKeys('SETTINGS_LANGUAGE_ALERT')
  static SETTINGS_NOTIFICATIONS = new LocKeys('SETTINGS_NOTIFICATIONS')
  static SETTINGS_NOTIFICATIONS_SOUND = new LocKeys(
    'SETTINGS_NOTIFICATIONS_SOUND'
  )
  static SETTINGS_NOTIFICATIONS_VIBRATION = new LocKeys(
    'SETTINGS_NOTIFICATIONS_VIBRATION'
  )
  static SETTINGS_NOTIFICATIONS_NIGHTMOD = new LocKeys(
    'SETTINGS_NOTIFICATIONS_NIGHTMOD'
  )
  static SETTINGS_NOTIFICATIONS_NIGHTMOD_DESC = new LocKeys(
    'SETTINGS_NOTIFICATIONS_NIGHTMOD_DESC'
  )
  static SETTINGS_REPORT = new LocKeys('SETTINGS_REPORT')
  static SETTINGS_VERSION = new LocKeys('SETTINGS_VERSION')
  static SETTINGS_CONFIGURATION = new LocKeys('SETTINGS_CONFIGURATION')
  static SETTINGS_SCHEDULE = new LocKeys('SETTINGS_SCHEDULE')
  static SETTINGS_RESET_ALERT = new LocKeys('SETTINGS_RESET_ALERT')
  static SETTINGS_RESET_ALERT_DESC = new LocKeys('SETTINGS_RESET_ALERT_DESC')
  static SETTINGS_RESET_ALERT_OPTION_DESC = new LocKeys(
    'SETTINGS_RESET_ALERT_OPTION_DESC'
  )
  static SETTINGS_CACHE = new LocKeys('SETTINGS_CACHE')
  static SETTINGS_CACHE_SIZE = new LocKeys('SETTINGS_CACHE_SIZE')
  static SETTINGS_LAST_UPLOAD_TO_SERVER = new LocKeys(
    'SETTINGS_LAST_UPLOAD_TO_SERVER'
  )
  static LANGUAGE_ENGLISH = new LocKeys('LANGUAGE_ENGLISH')
  static LANGUAGE_SPANISH = new LocKeys('LANGUAGE_SPANISH')
  static LANGUAGE_ITALIAN = new LocKeys('LANGUAGE_ITALIAN')
  static LANGUAGE_GERMAN = new LocKeys('LANGUAGE_GERMAN')
  static LANGUAGE_DANISH = new LocKeys('LANGUAGE_DANISH')
  static LANGUAGE_DUTCH = new LocKeys('LANGUAGE_DUTCH')
  static BTN_ENROL_ENROL = new LocKeys('BTN_ENROL_ENROL')
  static BTN_ENROL_SCAN = new LocKeys('BTN_ENROL_SCAN')
  static BTN_FINISH = new LocKeys('BTN_FINISH')
  static BTN_DONE = new LocKeys('BTN_DONE')
  static BTN_START = new LocKeys('BTN_START')
  static BTN_STOP = new LocKeys('BTN_STOP')
  static BTN_RESET = new LocKeys('BTN_RESET')
  static BTN_RETRY = new LocKeys('BTN_RETRY')
  static BTN_AGREE = new LocKeys('BTN_AGREE')
  static BTN_DISAGREE = new LocKeys('BTN_DISAGREE')
  static BTN_OKAY = new LocKeys('BTN_OKAY')
  static BTN_SET = new LocKeys('BTN_SET')
  static BTN_CANCEL = new LocKeys('BTN_CANCEL')
  static BTN_BEGIN = new LocKeys('BTN_BEGIN')
  static BTN_NEXT = new LocKeys('BTN_NEXT')
  static BTN_PREVIOUS = new LocKeys('BTN_PREVIOUS')
  static BTN_CLOSE = new LocKeys('BTN_CLOSE')
  static BTN_SELECT = new LocKeys('BTN_SELECT')
  static BTN_YES = new LocKeys('BTN_YES')
  static BTN_NO = new LocKeys('BTN_NO')
  static BTN_TRY_AGAIN = new LocKeys('BTN_TRY_AGAIN')
  static STATUS_LOADING = new LocKeys('STATUS_LOADING')
  static STATUS_SUCCESS = new LocKeys('STATUS_SUCCESS')
  static STATUS_FAILURE = new LocKeys('STATUS_FAILURE')
  static STATUS_NOW = new LocKeys('STATUS_NOW')
  static NOTIFICATION_TEST_REMINDER_NOW = new LocKeys(
    'NOTIFICATION_TEST_REMINDER_NOW'
  )
  static NOTIFICATION_TEST_REMINDER_NOW_DESC = new LocKeys(
    'NOTIFICATION_TEST_REMINDER_NOW_DESC'
  )
  static NOTIFICATION_REMINDER_SOON = new LocKeys('NOTIFICATION_REMINDER_SOON')
  static NOTIFICATION_REMINDER_SOON_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_SOON_DESC'
  )
  static NOTIFICATION_REMINDER_NOW = new LocKeys('NOTIFICATION_REMINDER_NOW')
  static NOTIFICATION_REMINDER_NOW_DESC_1 = new LocKeys(
    'NOTIFICATION_REMINDER_NOW_DESC_1'
  )
  static NOTIFICATION_REMINDER_NOW_DESC_2 = new LocKeys(
    'NOTIFICATION_REMINDER_NOW_DESC_2'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN_DESC'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN_ALERT_DEFAULT_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN_ALERT_DEFAULT_DESC'
  )
  static NOTIFICATION_REMINDER_FORGOTTEN_ALERT_LASTOFNIGHT_DESC = new LocKeys(
    'NOTIFICATION_REMINDER_FORGOTTEN_ALERT_LASTOFNIGHT_DESC'
  )
  static MEASURE_PROGRESS = new LocKeys('MEASURE_PROGRESS')
  static MEASURE_STEPS = new LocKeys('MEASURE_STEPS')
  static MEASURE_HEART_RATE = new LocKeys('MEASURE_HEART_RATE')
  static CREDITS_TITLE = new LocKeys('CREDITS_TITLE')
  static CREDITS_BODY = new LocKeys('CREDITS_BODY')
  static TASK_CALENDAR_TITLE = new LocKeys('TASK_CALENDAR_TITLE')
  static TASK_INFO_WARN = new LocKeys('TASK_INFO_WARN')
  static TASK_PROGRESS_COMPLETED = new LocKeys('TASK_PROGRESS_COMPLETED')
  static TASK_PROGRESS_TITLE = new LocKeys('TASK_PROGRESS_TITLE')
  static TASK_BAR_NEXT_TASK = new LocKeys('TASK_BAR_NEXT_TASK')
  static TASK_BAR_NOW_TASK = new LocKeys('TASK_BAR_NOW_TASK')
  static TASK_BAR_NEXT_TASK_SOON = new LocKeys('TASK_BAR_NEXT_TASK_SOON')
  static TASK_BAR_AFFIRMATION_1 = new LocKeys('TASK_BAR_AFFIRMATION_1')
  static TASK_BAR_AFFIRMATION_2 = new LocKeys('TASK_BAR_AFFIRMATION_2')
  static TASK_BAR_TASK_LEFT_1 = new LocKeys('TASK_BAR_TASK_LEFT_1')
  static TASK_BAR_TASK_LEFT_2 = new LocKeys('TASK_BAR_TASK_LEFT_2')
  static TASK_BAR_NO_TASK_1 = new LocKeys('TASK_BAR_NO_TASK_1')
  static TASK_BAR_NO_TASK_2 = new LocKeys('TASK_BAR_NO_TASK_2')
  static TASK_TIME_HOUR_SINGLE = new LocKeys('TASK_TIME_HOUR_SINGLE')
  static TASK_TIME_HOUR_MULTIPLE = new LocKeys('TASK_TIME_HOUR_MULTIPLE')
  static TASK_TIME_MINUTE_SINGLE = new LocKeys('TASK_TIME_MINUTE_SINGLE')
  static TASK_TIME_MINUTE_MULTIPLE = new LocKeys('TASK_TIME_MINUTE_MULTIPLE')
  static TESTING_NOTIFICATIONS = new LocKeys('TESTING_NOTIFICATIONS')
  static TESTING_NOTIFICATIONS_MESSAGE = new LocKeys(
    'TESTING_NOTIFICATIONS_MESSAGE'
  )
  static CLOSE_APP = new LocKeys('CLOSE_APP')
  static WARNING_DO_NOT_CLOSE_APP = new LocKeys('WARNING_DO_NOT_CLOSE_APP')
  static CONFIG_ERROR_DESC = new LocKeys('CONFIG_ERROR_DESC')
  static AUDIO_TASK_ALERT = new LocKeys('AUDIO_TASK_ALERT')
  static AUDIO_TASK_ALERT_DESC = new LocKeys('AUDIO_TASK_ALERT_DESC')
  static AUDIO_TASK_ATTEMPT_ALERT = new LocKeys('AUDIO_TASK_ATTEMPT_ALERT')
  static AUDIO_TASK_HAPPY_ALERT = new LocKeys('AUDIO_TASK_HAPPY_ALERT')
  static SPLASH_STATUS_UPDATING_CONFIG = new LocKeys(
    'SPLASH_STATUS_UPDATING_CONFIG'
  )
  static SPLASH_STATUS_SENDING_LOGS = new LocKeys('SPLASH_STATUS_SENDING_LOGS')

  constructor(public value: string) {}

  toString() {
    return this.value
  }
}
