/**
 * App Server
 * RADAR App Server Api Documentation
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FcmNotificationDto {
  appPackage?: string
  body?: string
  delivered?: boolean
  fcmMessageId?: string
  id?: number
  scheduledTime?: Date
  sourceId?: string
  sourceType?: string
  title?: string
  ttlSeconds?: number
  type?: string
}
