export const q = [
    {
        "field_name": "pacq_instructions_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Participant Cost Questionnaire",
        "field_type": "descriptive",
        "field_label": "<div class=\"rich-text-field-label\"><p>Thank you for agreeing to participate in the RECURRENT-GB study.<br><br>We would be grateful if you could complete this questionnaire about your use of health services and costs to you due to your glioblastoma. If a proxy is filling in this questionnaire, please complete the questions as though you are the patient.<br><br>If you have any questions about the study or this questionnaire, please do not hesitate to contact a member of the study team on recurrentgb@nds.ox.ac.uk or call 07917 101649 (Monday to Friday, 9-4pm), there is an answering machine for messages outside of these times, or contact your local clinical team.</p></div>",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_date",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Today's date:",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "date_dmy",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_papr",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "radio",
        "field_label": "Are you the participant or the proxy?",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Participant"
            },
            {
                "code": "2",
                "label": "Proxy"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_papr_warn",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "descriptive",
        "field_label": "<div class=\"rich-text-field-label\">Please answer as if you are the participant.</div>",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_papr] = '2'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_residence",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "About You",
        "field_type": "radio",
        "field_label": "Where do you currently live?",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "At home living by yourself"
            },
            {
                "code": "2",
                "label": "At home living with others"
            },
            {
                "code": "3",
                "label": "Residential care home"
            },
            {
                "code": "4",
                "label": "At the home of another (e.g., family member or friend)"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_about",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_formal_care",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Current formal care received",
        "field_type": "yesno",
        "field_label": "Have you received any formal care in the last week?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "Formal care includes any additional support you may receive from a healthcare visitor, NHS continuing care, or other supports provided by the NHS, social care, or your local authority.",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_care_hours",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "How many hours of formal care did you receive in the last week? If you received 24/7 care please enter 168.\nPlease answer with the estimated number of hours of care you have received. If you have a formal live-in carer please use the question below.",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "168",
        "identifier": "",
        "branching_logic": "[pacq_formal_care] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_hours",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Do you have a formal live-in carer (i.e., a carer who stays overnight that is not a family member or friend)?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_formal_care] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_home_changes_yn",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Additional costs to you due to your glioblastoma",
        "field_type": "yesno",
        "field_label": "Have you or your household made any changes or adaptations to your home because of your glioblastoma in the last 3 months? This may be to support your safety, mobility, or independence.",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_adaptation_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about the cost of these adaptions to you or your family and friends over the last 3 months. If some or all of the costs were paid for by a local authority, charity or the NHS, please tick the box below. We understand that it is difficult to remember the exact cost. Please give us your best guess.",
        "field_type": "text",
        "field_label": "Type of home adaptation",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_cost_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "200000",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_paid_by_other_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Costs were paid or partially paid by the NHS, a charity, or local authority",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_add_another_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Do you want to add another additional cost?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_adaptation_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Type of home adaptation",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_cost_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "200000",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_paid_by_other_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Costs were paid or partially paid by the NHS, a charity, or local authority",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_add_another_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Do you want to add another additional cost?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_adaptation_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Type of home adaptation",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_cost_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "200000",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_paid_by_other_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Costs were paid or partially paid by the NHS, a charity, or local authority",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_add_another_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Do you want to add another additional cost?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_adaptation_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Type of home adaptation",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_3] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_cost_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "200000",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_3] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_paid_by_other_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "yesno",
        "field_label": "Costs were paid or partially paid by the NHS, a charity, or local authority",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_home_changes_yn] = '1' and [pacq_add_another_3] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_extra_costs_yn",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "yesno",
        "field_label": "Have you, or your family and friends, incurred any other costs, that you've not told us about already, due to your glioblastoma in the last three months.",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "Costs may include additional travel expenses, over-the-counter medications, increased energy bills, private healthcare, or any other costs you've incurred due to your glioblastoma",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_type_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Type of cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_cost_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "10000",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_add_another_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "yesno",
        "field_label": "Do you have any other additional costs?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_type_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Type of cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_cost_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "10000",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_add_another_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "yesno",
        "field_label": "Do you have any other additional costs?",
        "select_choices_or_calculations": [
            {
                "code": "0",
                "label": "No"
            },
            {
                "code": "1",
                "label": "Yes"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_type_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Type of cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_cost_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "10000",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_add_another_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "yesno",
        "field_label": "Do you have any other additional costs?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_type_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Type of cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_3] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_ecost_cost_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Please tell us about these additional costs / expenses below. We understand that it is difficult to remember everything. Please give your best guess.",
        "field_type": "text",
        "field_label": "Approximate cost",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "number",
        "text_validation_min": "0",
        "text_validation_max": "10000",
        "identifier": "",
        "branching_logic": "[pacq_extra_costs_yn] = '1' and [pacq_ecost_add_another_3] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_gp_in_person",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Community based healthcare use",
        "field_type": "text",
        "field_label": "In the last 3 months, how many times have you had an appointment with a doctor (GP) at a GP surgery, health centre or walk-in centre?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "20",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_hcu",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_gp_online",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "In the last 3 months, how many times have you had an appointment with a doctor (GP) over the telephone or online?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "20",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_hcu",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_gp_home",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "In the last 3 months, how many times have you had an appointment with a doctor (GP) at home?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "20",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_hcu",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_other_in_person",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "In the last 3 months, how many times have you had an appointment with any other NHS healthcare professionals or NHS healthcare services at a GP surgery, health centre or walk-in centre?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "20",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_hcu",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_other_online",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "In the last 3 months, how many times have you had an appointment with any other NHS healthcare professionals or NHS healthcare services (e.g. [NHS 111]) over the telephone or online?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "20",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_hcu",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_other_home",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "In the last 3 months, how many times have you had an appointment with any other NHS healthcare professionals or NHS healthcare services at home?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "0",
        "text_validation_max": "20",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "pacq_g_hcu",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescription_yn",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "Prescribed medications",
        "field_type": "yesno",
        "field_label": "In the last 3 months, have you picked up or received any prescribed medications due to your glioblastoma?",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "If not prescribed, please press 'Next'.",
        "field_type": "checkbox",
        "field_label": "Dexamethasone",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Select if prescribed"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_prescription_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescriptions_1",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Dexamethasone (Number of times picked up or received from pharmacy in the last 3 months?)",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "",
        "text_validation_max": "10",
        "identifier": "",
        "branching_logic": "[pacq_medications_1] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "If not prescribed, please press 'Next'.",
        "field_type": "checkbox",
        "field_label": "Levetiracetam (Keppra)",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Select if prescribed"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_prescription_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescriptions_2",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Levetiracetam (Keppra) (Number of times picked up or received from pharmacy in the last 3 months?)",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "",
        "text_validation_max": "10",
        "identifier": "",
        "branching_logic": "[pacq_medications_2] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "If not prescribed, please press 'Next'.",
        "field_type": "checkbox",
        "field_label": "Sodium valproate (Epilim)",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Select if prescribed"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_prescription_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescriptions_3",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Sodium valproate (Epilim) (Number of times picked up or received from pharmacy in the last 3 months?)",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "",
        "text_validation_max": "10",
        "identifier": "",
        "branching_logic": "[pacq_medications_3] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "If not prescribed, please press 'Next'.",
        "field_type": "checkbox",
        "field_label": "Omeprazole/Esomeprazole/Lansoprazole/Pantoprazole",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Select if prescribed"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_prescription_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescriptions_4",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Omeprazole/Esomeprazole/Lansoprazole/Pantoprazole (Number of times picked up or received from pharmacy in the last 3 months?)",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "",
        "text_validation_max": "10",
        "identifier": "",
        "branching_logic": "[pacq_medications_4] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_5",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "If not prescribed, please press 'Next'.",
        "field_type": "checkbox",
        "field_label": "Ranitidine/Famotidine/Cimetidine",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Select if prescribed"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_prescription_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescriptions_5",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Ranitidine/Famotidine/Cimetidine (Number of times picked up or received from pharmacy in the last 3 months?)",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "integer",
        "text_validation_min": "",
        "text_validation_max": "10",
        "identifier": "",
        "branching_logic": "[pacq_medications_5] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_88",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "If not prescribed, please press 'Next'.",
        "field_type": "checkbox",
        "field_label": "Other",
        "select_choices_or_calculations": [
            {
                "code": "1",
                "label": "Select if prescribed"
            }
        ],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_prescription_yn] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_medications_other",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Please specify",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_medications_88] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    },
    {
        "field_name": "pacq_prescriptions_other",
        "form_name": "participant_costs_3_month_questionnaire",
        "section_header": "",
        "field_type": "text",
        "field_label": "Other (Number of times picked up or received from pharmacy in the last 3 months?)",
        "select_choices_or_calculations": [],
        "field_note": "",
        "text_validation_type_or_show_slider_number": "",
        "text_validation_min": "",
        "text_validation_max": "",
        "identifier": "",
        "branching_logic": "[pacq_medications_88] = '1'",
        "required_field": "",
        "custom_alignment": "",
        "question_number": "",
        "matrix_group_name": "",
        "matrix_ranking": "",
        "field_annotation": "",
        "evaluated_logic": ""
    }
]